#!/usr/bin/env bash
# Run GSM exploration rollouts from SFT adapters and score them with GPT-5.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BASE_LAUNCHER="${BASE_LAUNCHER:-${SCRIPT_DIR}/run_gsm_correction_vllm_8gpu.sh}"
PROJECT_ROOT="${PROJECT_ROOT:-/data/wangyuheng/jca}"

SFT_TAG="${SFT_TAG:-gsm_corr30_balanced_20260723_v2}"
MODE="sft_lora_mas"
MAS_SCRIPT="gsm/scripts/run_gsm_judge_rl_rollout.py"
DATA_PATH="${DATA_PATH:-${PROJECT_ROOT}/Math/data/GSM-HARD/splits/gsmhardv2_train.jsonl}"
START="${START:-0}"
LIMIT="${LIMIT:-500}"
NUM_ROLLOUTS="${NUM_ROLLOUTS:-8}"
T_MAX="${T_MAX:-8}"
START_AGENT="${START_AGENT:-A1}"
ALLOW_NON_A1_START="${ALLOW_NON_A1_START:-0}"
MIN_AGENTS_BEFORE_STOP="${MIN_AGENTS_BEFORE_STOP:-1}"
ENFORCE_COLLABORATION_POLICY="${ENFORCE_COLLABORATION_POLICY:-0}"

[[ "$ALLOW_NON_A1_START" == "0" || "$ALLOW_NON_A1_START" == "1" ]] || {
  echo "[fatal] ALLOW_NON_A1_START must be 0 or 1" >&2
  exit 1
}
if [[ "$ALLOW_NON_A1_START" == "1" ]]; then
  [[ "$START_AGENT" == "A1" || "$START_AGENT" == "A2" || "$START_AGENT" == "A3" ]] || {
    echo "[fatal] START_AGENT must be A1, A2, or A3" >&2
    exit 1
  }
else
  [[ "$START_AGENT" == "A1" ]] || {
    echo "[fatal] START_AGENT must remain A1 unless ALLOW_NON_A1_START=1" >&2
    exit 1
  }
fi

MAX_CONCURRENCY="${MAX_CONCURRENCY:-4}"
MAX_NEW_TOKENS="${MAX_NEW_TOKENS:-1024}"
TEMPERATURE="${TEMPERATURE:-0.9}"
TOP_P="${TOP_P:-0.95}"
LOG_RAW_CHARS="${LOG_RAW_CHARS:-0}"
RESUME="${RESUME:-1}"
GROUP_RETRIES="${GROUP_RETRIES:-5}"
STEP_RETRIES="${STEP_RETRIES:-4}"

JUDGE_MODEL="${JUDGE_MODEL:-gpt-5}"
JUDGE_TEMPERATURE="${JUDGE_TEMPERATURE:-0.0}"
JUDGE_TOP_P="${JUDGE_TOP_P:-0.95}"
JUDGE_MAX_TOKENS="${JUDGE_MAX_TOKENS:-16384}"
JUDGE_REASONING_EFFORT="${JUDGE_REASONING_EFFORT:-low}"
JUDGE_PARSE_RETRIES="${JUDGE_PARSE_RETRIES:-2}"
ALLOW_JUDGE_FAILURE="${ALLOW_JUDGE_FAILURE:-0}"
ALPHA="${ALPHA:-0.6}"
TASK_METRIC="${TASK_METRIC:-em}"

MODEL_A1="${MODEL_A1:-/data/wangyuheng/models/Qwen3-1.7B}"
MODEL_A2="${MODEL_A2:-/data/wangyuheng/models/Qwen3-4B}"
MODEL_A3="${MODEL_A3:-/data/wangyuheng/models/Qwen3-8B}"
ADAPTER_A1="${ADAPTER_A1:-${PROJECT_ROOT}/sft_runs/${SFT_TAG}/A1/final}"
ADAPTER_A2="${ADAPTER_A2:-${PROJECT_ROOT}/sft_runs/${SFT_TAG}/A2/final}"
ADAPTER_A3="${ADAPTER_A3:-${PROJECT_ROOT}/sft_runs/${SFT_TAG}/A3/final}"

CORRECTION_FRACTION="0.30"
SFT_PLAN_OFFSET="-1"
CYCLE_DATA="0"
SFT_WARMUP_PROMPT="0"
SFT_CONTROLLED_GENERATION="0"

RUN_ID="${RUN_ID:-$(date +%Y%m%d_%H%M%S)_gsm_judge_rl}"
LOG_DIR="${LOG_DIR:-logs/gsm_judge_rl_rollout}"
OUTPUT_DIR="${OUTPUT_DIR:-rl_data/gsm}"
OUTPUT_PATH="${OUTPUT_PATH:-${OUTPUT_DIR}/${RUN_ID}.jsonl}"

export PROJECT_ROOT SFT_TAG MODE MAS_SCRIPT DATA_PATH START LIMIT NUM_ROLLOUTS
export T_MAX START_AGENT MIN_AGENTS_BEFORE_STOP MAX_CONCURRENCY MAX_NEW_TOKENS
export ENFORCE_COLLABORATION_POLICY
export TEMPERATURE TOP_P LOG_RAW_CHARS RESUME GROUP_RETRIES STEP_RETRIES
export JUDGE_MODEL JUDGE_TEMPERATURE
export JUDGE_TOP_P JUDGE_MAX_TOKENS JUDGE_REASONING_EFFORT JUDGE_PARSE_RETRIES
export ALLOW_JUDGE_FAILURE ALPHA TASK_METRIC MODEL_A1 MODEL_A2 MODEL_A3
export ADAPTER_A1 ADAPTER_A2 ADAPTER_A3 CORRECTION_FRACTION SFT_PLAN_OFFSET
export CYCLE_DATA SFT_WARMUP_PROMPT SFT_CONTROLLED_GENERATION RUN_ID LOG_DIR
export OUTPUT_DIR OUTPUT_PATH

exec bash "$BASE_LAUNCHER" "$@"
