"""vLLM fleet lifecycle: launch, health, LoRA hot-swap, teardown.

vLLM 0.18 exposes ``/v1/load_lora_adapter`` (gated on
``VLLM_ALLOW_RUNTIME_LORA_UPDATING=1``), and re-loading an existing name with
``load_inplace: true`` reuses the same ``lora_int_id``. That lets each iteration
publish new adapters without restarting a server.

The hazard this class exists to prevent: vLLM keys prefix-cache KV blocks on the
LoRA *name* only (``vllm/v1/core/kv_cache_utils.py:_gen_lora_extra_hash_keys``),
never on the adapter's path or contents. With ``inplace`` naming, blocks computed
under iteration k would be reused at iteration k+1 -- the rollout would be partly
generated by the previous policy, silently breaking on-policy-ness. So
``inplace`` forces prefix caching off, and ``versioned`` naming exists for when
you want the caching back.

Every swap is verified (``/v1/models`` plus a canary generation) and a failed
swap stops the run rather than letting it continue on a stale policy.
"""
from __future__ import annotations

import json
import os
import signal
import subprocess
import time
import urllib.error
import urllib.request
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from .config import AGENTS, Config


def _post(url: str, payload: dict[str, Any], *, timeout: float = 120.0) -> tuple[int, str]:
    request = urllib.request.Request(
        url,
        data=json.dumps(payload).encode("utf-8"),
        headers={"Content-Type": "application/json"},
        method="POST",
    )
    try:
        with urllib.request.urlopen(request, timeout=timeout) as response:
            return int(response.status), response.read().decode("utf-8", "replace")
    except urllib.error.HTTPError as exc:
        return int(exc.code), exc.read().decode("utf-8", "replace")


def _get(url: str, *, timeout: float = 30.0) -> tuple[int, str]:
    try:
        with urllib.request.urlopen(url, timeout=timeout) as response:
            return int(response.status), response.read().decode("utf-8", "replace")
    except urllib.error.HTTPError as exc:
        return int(exc.code), exc.read().decode("utf-8", "replace")
    except Exception as exc:  # noqa: BLE001
        return 0, str(exc)


@dataclass
class ServerHandle:
    agent: str
    base_url: str
    process: subprocess.Popen | None = None
    log_path: Path | None = None
    served_name: str = ""


class VLLMFleet:
    """Three servers, one per agent, with adapter publishing."""

    def __init__(self, config: Config, *, log_dir: Path) -> None:
        self.config = config
        self.log_dir = Path(log_dir)
        self.log_dir.mkdir(parents=True, exist_ok=True)
        self.servers: dict[str, ServerHandle] = {}
        self.current_names: dict[str, str] = {a: f"{a}_base" for a in AGENTS}
        self.swap_log: list[dict[str, Any]] = []

    # -- lifecycle ----------------------------------------------------------
    def launch(self) -> None:
        serving = self.config.serving
        for agent in AGENTS:
            port = serving.ports[agent]
            gpus = serving.serve_gpus[agent]
            tp = len([g for g in gpus.split(",") if g.strip()])
            log_path = self.log_dir / f"serve_{agent}.log"
            cmd = [
                serving.vllm_python, "-m", "vllm.entrypoints.openai.api_server",
                "--host", serving.host,
                "--port", str(port),
                "--model", serving.models[agent],
                "--served-model-name", f"{agent}_base",
                "--tensor-parallel-size", str(max(1, tp)),
                "--dtype", "bfloat16",
                "--gpu-memory-utilization", str(serving.gpu_memory_utilization[agent]),
                "--max-model-len", str(serving.max_model_len),
                "--trust-remote-code",
                "--enable-lora",
                "--max-lora-rank", str(self.config.train.lora.r),
                # 2 slots so versioned naming can hold old and new at once.
                "--max-loras", "2",
                "--max-cpu-loras", "4",
                "--disable-uvicorn-access-log",
            ]
            if not serving.enable_prefix_caching:
                cmd.append("--no-enable-prefix-caching")
            if os.environ.get("MAGRPO_DISABLE_CUSTOM_ALL_REDUCE", "0") == "1":
                cmd.append("--disable-custom-all-reduce")
            env = dict(os.environ)
            allocated = os.environ.get("CUDA_VISIBLE_DEVICES", "").split(",")
            if allocated != [""]:
                env["CUDA_VISIBLE_DEVICES"] = ",".join(allocated[int(index)] for index in gpus.split(","))
            else:
                env["CUDA_VISIBLE_DEVICES"] = gpus
            env["VLLM_ALLOW_RUNTIME_LORA_UPDATING"] = "1"
            env["VLLM_SERVER_DEV_MODE"] = "1"
            handle = open(log_path, "w", encoding="utf-8")
            process = subprocess.Popen(cmd, stdout=handle, stderr=subprocess.STDOUT, env=env, start_new_session=True)
            handle.close()
            self.servers[agent] = ServerHandle(
                agent=agent,
                base_url=f"http://{serving.host}:{port}/v1",
                process=process,
                log_path=log_path,
                served_name=f"{agent}_base",
            )

    def wait_healthy(self, timeout_s: int | None = None) -> None:
        timeout_s = timeout_s or self.config.serving.startup_timeout_s
        deadline = time.time() + timeout_s
        pending = set(self.servers)
        while pending and time.time() < deadline:
            for agent in sorted(pending):
                process = self.servers[agent].process
                if process and process.poll() is not None:
                    log = self.servers[agent].log_path
                    tail = "\n".join(log.read_text(errors="replace").splitlines()[-30:]) if log else ""
                    raise RuntimeError(f"{agent}: vLLM exited with {process.returncode}\n{tail}")
                status, _ = _get(f"{self.servers[agent].base_url}/models", timeout=5.0)
                if status == 200:
                    pending.discard(agent)
            if pending:
                time.sleep(5.0)
        if pending:
            tails = []
            for agent in sorted(pending):
                log = self.servers[agent].log_path
                tail = ""
                if log and log.is_file():
                    tail = "\n".join(log.read_text(errors="replace").splitlines()[-15:])
                tails.append(f"--- {agent} ---\n{tail}")
            raise RuntimeError(
                f"vLLM servers not healthy after {timeout_s}s: {sorted(pending)}\n"
                + "\n".join(tails)
            )

    def shutdown(self) -> None:
        for handle in self.servers.values():
            if handle.process and handle.process.poll() is None:
                os.killpg(handle.process.pid, signal.SIGTERM)
        for handle in self.servers.values():
            if handle.process:
                try:
                    handle.process.wait(timeout=60)
                except subprocess.TimeoutExpired:
                    os.killpg(handle.process.pid, signal.SIGKILL)

    # -- adapter publishing -------------------------------------------------
    def adapter_name(self, agent: str, iteration: int) -> str:
        if self.config.serving.lora_naming == "versioned":
            return f"{agent}_it{iteration:04d}"
        return agent

    def publish_adapters(
        self, iteration: int, paths: dict[str, Path]
    ) -> dict[str, str]:
        """Load each agent's new adapter and return the names to request next."""
        naming = self.config.serving.lora_naming
        published: dict[str, str] = {}
        for agent, path in paths.items():
            handle = self.servers[agent]
            name = self.adapter_name(agent, iteration)
            previous = self.current_names.get(agent)
            payload = {
                "lora_name": name,
                "lora_path": str(Path(path).resolve()),
                # Required whenever the name already exists; harmless otherwise.
                "load_inplace": naming == "inplace",
            }
            status, body = _post(f"{handle.base_url}/load_lora_adapter", payload)
            if status != 200:
                raise RuntimeError(
                    f"{agent}: LoRA hot-swap failed at iteration {iteration} "
                    f"(HTTP {status}): {body[:400]}"
                )
            self.swap_log.append(
                {"iteration": iteration, "agent": agent, **payload, "status": status}
            )
            self._verify(handle, name, agent)
            if naming == "versioned" and previous and previous != name and previous != f"{agent}_base":
                _post(f"{handle.base_url}/unload_lora_adapter", {"lora_name": previous})
            self.current_names[agent] = name
            handle.served_name = name
            published[agent] = name
        return published

    def _verify(self, handle: ServerHandle, name: str, agent: str) -> None:
        """The swap is only real if the model lists AND answers under that name."""
        status, body = _get(f"{handle.base_url}/models")
        if status != 200 or name not in body:
            raise RuntimeError(
                f"{agent}: adapter {name!r} missing from /v1/models after swap"
            )
        status, body = _post(
            f"{handle.base_url}/chat/completions",
            {
                "model": name,
                "messages": [{"role": "user", "content": "ping"}],
                "max_tokens": 1,
                "temperature": 0.0,
            },
            timeout=120.0,
        )
        if status != 200:
            raise RuntimeError(
                f"{agent}: canary generation failed after swap (HTTP {status}): "
                f"{body[:300]}"
            )

    # -- sleep/wake (timeshare plan) ----------------------------------------
    def sleep(self, level: int = 1) -> None:
        for handle in self.servers.values():
            _post(f"{handle.base_url.rsplit('/v1', 1)[0]}/sleep?level={level}", {})
        self._await_sleep(True)

    def wake(self) -> None:
        for handle in self.servers.values():
            _post(f"{handle.base_url.rsplit('/v1', 1)[0]}/wake_up", {})
        self._await_sleep(False)

    def _await_sleep(self, target: bool, timeout_s: int = 300) -> None:
        """/sleep and /wake_up return before completing, so poll /is_sleeping."""
        deadline = time.time() + timeout_s
        while time.time() < deadline:
            states = []
            for handle in self.servers.values():
                root = handle.base_url.rsplit("/v1", 1)[0]
                status, body = _get(f"{root}/is_sleeping", timeout=10.0)
                states.append(status == 200 and "true" in body.lower())
            if all(s == target for s in states):
                return
            time.sleep(2.0)
        raise RuntimeError(f"servers did not reach is_sleeping={target} in {timeout_s}s")

    def base_urls(self) -> dict[str, str]:
        return {a: h.base_url for a, h in self.servers.items()}


class MockFleet:
    """In-process HTTP stand-in used by the CPU smoke test.

    Implements the endpoints the loop touches and records every swap so tests
    can assert the adapter path and ``load_inplace`` flag were correct.
    """

    def __init__(self, config: Config, *, log_dir: Path | None = None) -> None:
        self.config = config
        self.swap_log: list[dict[str, Any]] = []
        self.current_names = {a: f"{a}_base" for a in AGENTS}
        self.sleeping = False

    def launch(self) -> None:  # nothing to start
        return

    def wait_healthy(self, timeout_s: int | None = None) -> None:
        return

    def shutdown(self) -> None:
        return

    def adapter_name(self, agent: str, iteration: int) -> str:
        if self.config.serving.lora_naming == "versioned":
            return f"{agent}_it{iteration:04d}"
        return agent

    def publish_adapters(self, iteration: int, paths: dict[str, Path]) -> dict[str, str]:
        published = {}
        for agent, path in paths.items():
            resolved = Path(path).resolve()
            if not resolved.is_dir():
                raise RuntimeError(f"{agent}: adapter path does not exist: {resolved}")
            name = self.adapter_name(agent, iteration)
            self.swap_log.append(
                {
                    "iteration": iteration,
                    "agent": agent,
                    "lora_name": name,
                    "lora_path": str(resolved),
                    "load_inplace": self.config.serving.lora_naming == "inplace",
                    "status": 200,
                }
            )
            self.current_names[agent] = name
            published[agent] = name
        return published

    def sleep(self, level: int = 1) -> None:
        self.sleeping = True

    def wake(self) -> None:
        self.sleeping = False

    def base_urls(self) -> dict[str, str]:
        return {a: f"mock://{a}" for a in AGENTS}


def build_fleet(config: Config, *, log_dir: Path):
    return MockFleet(config, log_dir=log_dir) if config.mock else VLLMFleet(config, log_dir=log_dir)
