#!/usr/bin/env bash
# v13 judge-only refresh: Qwen3-14B thinking plus compact canonical scoring.

set -euo pipefail

PROJECT_ROOT="${PROJECT_ROOT:-/data/wangyuheng/jca}"
OUTPUT_PATH="${V13_14B_SOURCE_OUTPUT:-${PROJECT_ROOT}/rl_data/gsm/judge_rl/v13_14b/source_rejudged.jsonl}"
STATS_OUTPUT="${V13_14B_STATS_OUTPUT:-${PROJECT_ROOT}/rl_data/gsm/judge_rl/v13_14b/source_rejudge_stats.json}"
LOG_DIR="${V13_14B_LOG_DIR:-${PROJECT_ROOT}/logs/gsm_judge_rl/v13_14b_rejudge}"
RUN_ID="${V13_14B_RUN_ID:-$(date +%Y%m%d_%H%M%S)_v13_14b_rejudge}"
JUDGE_CONCURRENCY="${JUDGE_CONCURRENCY:-16}"
GROUP_RETRIES="${GROUP_RETRIES:-2}"
JUDGE_PARSE_RETRIES="${JUDGE_PARSE_RETRIES:-2}"
JUDGE_TEMPERATURE="${JUDGE_TEMPERATURE:-0.6}"
AUTO_RESUME_PASSES="${AUTO_RESUME_PASSES:-5}"
JCA_JUDGE_COMPACT_FALLBACK_DISABLE_THINKING="${JCA_JUDGE_COMPACT_FALLBACK_DISABLE_THINKING:-1}"

exec env \
  REJUDGE_SCRIPT="${PROJECT_ROOT}/gsm/scripts/rejudge_gsm_collaboration_v4.py" \
  OUTPUT_PATH="$OUTPUT_PATH" \
  STATS_OUTPUT="$STATS_OUTPUT" \
  LOG_DIR="$LOG_DIR" \
  RUN_ID="$RUN_ID" \
  ENABLE_THINKING=1 \
  JCA_JUDGE_DISABLE_THINKING=0 \
  JCA_JUDGE_ENABLE_THINKING=1 \
  CHAT_TEMPLATE_KWARGS='{"enable_thinking":true}' \
  MAX_MODEL_LEN="${MAX_MODEL_LEN:-32768}" \
  JUDGE_CONCURRENCY="$JUDGE_CONCURRENCY" \
  GROUP_RETRIES="$GROUP_RETRIES" \
  JUDGE_PARSE_RETRIES="$JUDGE_PARSE_RETRIES" \
  JUDGE_TEMPERATURE="$JUDGE_TEMPERATURE" \
  AUTO_RESUME_PASSES="$AUTO_RESUME_PASSES" \
  JCA_JUDGE_COMPACT_FALLBACK_DISABLE_THINKING="$JCA_JUDGE_COMPACT_FALLBACK_DISABLE_THINKING" \
  JUDGE_MAX_TOKENS="${JUDGE_MAX_TOKENS:-8192}" \
  bash "${PROJECT_ROOT}/scripts/gsm_judge_rl/rejudge_gsm_qwen14b.sh"
